version: '2'

services:
  web:
    container_name: web
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - sikao
  php:
    container_name: php
    build: ./fpm
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - sikao
  # database:
  #   image: mysql:latest
  #   ports:
  #     - 12000:3306
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: test
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   volumes:
  #     - ./database:/var/lib/mysql

networks:
  sikao:
    driver: bridge