version: '2'

services:
  web:
    container_name: web
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - sikao
  php:
    container_name: php
    build: ./fpm
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - sikao
  database:
    container_name: database
    image: mysql:latest
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database:/var/lib/mysql

networks:
  sikao:
    driver: bridge